In [97]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [98]:
df = pd.read_csv('tel_churn.csv')

In [99]:
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,True,False,False,True,True,...,False,False,True,False,True,False,False,False,False,False
1,1,0,56.95,1889.50,0,False,True,True,False,True,...,False,False,False,True,False,False,True,False,False,False
2,2,0,53.85,108.15,1,False,True,True,False,True,...,False,False,False,True,True,False,False,False,False,False
3,3,0,42.30,1840.75,0,False,True,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,4,0,70.70,151.65,1,True,False,True,False,True,...,False,False,True,False,True,False,False,False,False,False

In [100]:
df = df.drop('Unnamed: 0', axis=1)

In [101]:
df.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,0,True,False,False,True,True,False,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,0,False,True,True,False,True,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,1,False,True,True,False,True,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,0,False,True,True,False,True,False,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,1,True,False,True,False,True,False,...,False,False,True,False,True,False,False,False,False,False

In [102]:
# creating x and y variables

x = df.drop('Churn', axis=1)
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,True,False,False,True,True,False,True,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,False,True,True,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,False,True,True,False,True,False,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,False,True,True,False,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,True,False,True,False,True,False,False,...,False,False,True,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84.80,1990.50,False,True,False,True,False,True,False,...,False,False,False,True,False,True,False,False,False,False
7028,0,103.20,7362.90,True,False,False,True,False,True,False,...,False,True,False,False,False,False,False,False,False,True
7029,0,29.60,346.45,True,False,False,True,False,True,True,...,False,False,True,False,True,False,False,False,False,False
7030,1,74.40,306.60,False,True,False,True,True,False,False,...,False,False,False,True,True,False,False,False,False,False
7031,0,105.65,6844.50,False,True,True,False,True,False,False,...,True,False,False,False,False,False,False,False,False,True

In [103]:
y = df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [104]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

### **Decision Tree Classifier**

In [105]:
model_dt = DecisionTreeClassifier(criterion='gini', random_state=100, max_depth=6, min_samples_leaf=8)

In [106]:
model_dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [107]:
y_pred = model_dt.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1], shape=(1407,))

##### -> we want to compare predicted y values to actual y values

In [108]:
model_dt.score(x_test, y_pred)

1.0

#### -> this shows full accuracy

In [109]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.81      0.90      0.85      1034
           1       0.59      0.42      0.49       373

    accuracy                           0.77      1407
   macro avg       0.70      0.66      0.67      1407
weighted avg       0.75      0.77      0.76      1407

In [110]:
print(confusion_matrix(y_test, y_pred))

[[926 108]
 [215 158]]

#### **SMOTEENN** - class to perform over-sampling using SMOTE and cleaning using ENN.

##### **SMOTEENN is a data resampling technique used to handle class imbalance by combining oversampling and undersampling methods.**

In [111]:
sm = SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x,y)

In [112]:
xr_train, xr_test, yr_train, yr_test = train_test_split(x_resampled,y_resampled, test_size = 0.2)

In [113]:
model_dt_smote = DecisionTreeClassifier(criterion='gini', random_state=100, max_depth=6, min_samples_leaf=8)

In [114]:
model_dt_smote.fit(xr_train, yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [115]:
DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [116]:
y_pred_smote = model_dt_smote.predict(xr_test)

In [117]:
print(classification_report(yr_test, y_pred_smote, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.95      0.89      0.92       522
           1       0.92      0.96      0.94       662

    accuracy                           0.93      1184
   macro avg       0.93      0.93      0.93      1184
weighted avg       0.93      0.93      0.93      1184

In [118]:
print(confusion_matrix(yr_test, y_pred_smote))

[[467  55]
 [ 25 637]]

### **Random Forest Classifier**

In [119]:
from sklearn.ensemble import RandomForestClassifier

In [120]:


model_rf = RandomForestClassifier(n_estimators=100, criterion='gini', random_state=100, max_depth=6, min_samples_leaf=8)
model_rf.fit(x_train, y_train)
y_pred_rf = model_rf.predict(x_test)

In [121]:
print(classification_report(y_test, y_pred_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1034
           1       0.67      0.48      0.56       373

    accuracy                           0.80      1407
   macro avg       0.75      0.70      0.72      1407
weighted avg       0.79      0.80      0.79      1407

In [122]:
print(confusion_matrix(y_test, y_pred_rf))

[[945  89]
 [193 180]]

In [123]:
sm =SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x,y)

In [124]:
xr_train, xr_test, yr_train, yr_test = train_test_split(x_resampled, y_resampled, test_size = 0.2)

In [125]:
model_smote_rf = RandomForestClassifier(n_estimators=100, criterion='gini', random_state=100, max_depth=6, min_samples_leaf=8)

In [126]:
model_smote_rf.fit(xr_train, yr_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [127]:
y_pred_smote_rf = model_smote_rf.predict(xr_test)

In [128]:
print(classification_report(yr_test, y_pred_smote_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.95      0.91      0.93       506
           1       0.94      0.96      0.95       659

    accuracy                           0.94      1165
   macro avg       0.94      0.94      0.94      1165
weighted avg       0.94      0.94      0.94      1165

In [129]:
print(confusion_matrix(yr_test, y_pred_smote_rf))

[[462  44]
 [ 26 633]]

## **_Logistic Regression_**

In [130]:
from sklearn.linear_model import LogisticRegression

In [131]:
log_model = LogisticRegression(max_iter=5000)

log_model.fit(xr_train, yr_train)

LogisticRegression(max_iter=5000)

In [132]:
y_pred_log = log_model.predict(xr_test)

In [133]:
from sklearn.metrics import accuracy_score, classification_report

print("Logistic Regression Accuracy:", accuracy_score(yr_test, y_pred_log))
print(classification_report(yr_test, y_pred_log))

Logistic Regression Accuracy: 0.9467811158798283
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       506
           1       0.95      0.95      0.95       659

    accuracy                           0.95      1165
   macro avg       0.95      0.95      0.95      1165
weighted avg       0.95      0.95      0.95      1165

In [134]:
print(confusion_matrix(yr_test, y_pred_log))

[[475  31]
 [ 31 628]]

## **Support Vector Machine (SVM)**

In [135]:
from sklearn.svm import SVC

In [136]:
svm_model = SVC()

svm_model.fit(xr_train, yr_train)

SVC()

In [137]:
y_pred_svm = svm_model.predict(xr_test)

In [138]:
print("SVM Accuracy:", accuracy_score(yr_test, y_pred_svm))
print(classification_report(yr_test, y_pred_svm))

SVM Accuracy: 0.7484978540772532
              precision    recall  f1-score   support

           0       0.68      0.79      0.73       506
           1       0.81      0.72      0.76       659

    accuracy                           0.75      1165
   macro avg       0.75      0.75      0.75      1165
weighted avg       0.76      0.75      0.75      1165

In [139]:
print(confusion_matrix(yr_test, y_pred_svm))

[[398 108]
 [185 474]]

#### **For saving the model**

In [140]:
import pickle

In [141]:
filename = 'model.sav'

In [142]:
pickle.dump(model_smote_rf, open(filename, 'wb'))

In [143]:
load_model = pickle.load(open(filename, 'rb'))

In [144]:
load_model.score(xr_test, yr_test)

0.9399141630901288

####                   **it is shown 93.99% accuracy**

In [145]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

results = []

# Decision Tree
results.append([
    "Decision Tree",
    accuracy_score(yr_test, y_pred_smote),
    precision_score(yr_test, y_pred_smote),
    recall_score(yr_test, y_pred_smote),
    f1_score(yr_test, y_pred_smote)
])

# Random Forest
results.append([
    "Random Forest",
    accuracy_score(yr_test, y_pred_rf),
    precision_score(yr_test, y_pred_rf),
    recall_score(yr_test, y_pred_rf),
    f1_score(yr_test, y_pred_rf)
])

# Logistic Regression
results.append([
    "Logistic Regression",
    accuracy_score(yr_test, y_pred_log),
    precision_score(yr_test, y_pred_log),
    recall_score(yr_test, y_pred_log),
    f1_score(yr_test, y_pred_log)
])

# SVM
results.append([
    "SVM",
    accuracy_score(yr_test, y_pred_svm),
    precision_score(yr_test, y_pred_svm),
    recall_score(yr_test, y_pred_svm),
    f1_score(yr_test, y_pred_svm)
])

ValueError: Found input variables with inconsistent numbers of samples: [1165, 1184]